export const ACCOUNT_TEXT = {
  TITLE: "Account",
  SUBTITLE: "Manage your profile and security settings.",
  DEFAULT_USER_NAME: "User",
  PROFILE_SECTION_TITLE: "Profile",
  LABEL_FULL_NAME: "Full name",
  PLACEHOLDER_FULL_NAME: "Your full name",
  LABEL_EMAIL: "Email",
  PLACEHOLDER_EMAIL: "Leave blank to keep current email",
  ERROR_FULL_NAME_REQUIRED: "Full name is required.",
  ERROR_PROFILE_UPDATE: "Failed to update profile. Please try again.",
  SUCCESS_PROFILE_UPDATE: "Profile updated.",
  SAVING: "Saving…",
  SAVE_CHANGES: "Save changes",
  PASSWORD_SECTION_TITLE: "Change password",
  LABEL_CURRENT_PASSWORD: "Current password",
  PLACEHOLDER_CURRENT_PASSWORD: "Current password",
  LABEL_NEW_PASSWORD: "New password",
  PLACEHOLDER_NEW_PASSWORD: "Min. 8 characters",
  LABEL_CONFIRM_PASSWORD: "Confirm new password",
  PLACEHOLDER_CONFIRM_PASSWORD: "Repeat new password",
  ERROR_CURRENT_PASSWORD_REQUIRED: "Current password is required.",
  ERROR_PASSWORD_TOO_SHORT: "New password must be at least 8 characters.",
  ERROR_PASSWORD_MISMATCH: "Passwords do not match.",
  ERROR_PASSWORD_UPDATE: "Incorrect current password or request failed.",
  SUCCESS_PASSWORD_UPDATE: "Password changed successfully.",
  CHANGING_PASSWORD: "Saving…",
  CHANGE_PASSWORD: "Change password",
};

export const ACCOUNT_MESSAGE_TIMEOUT_MS = 3000;
